---
output: html_document
---

# Expression overview (Reads)

```{r, message=FALSE, warning=FALSE}
library(scater, quietly = TRUE)
options(stringsAsFactors = FALSE)
reads <- readRDS("blischak/reads.rds")
reads.qc <- reads[fData(reads)$use, pData(reads)$use]
endog_genes <- !fData(reads.qc)$is_feature_control
```

```{r, echo=FALSE}
library(knitr)
opts_chunk$set(out.width='90%', fig.align = 'center')
```

```{r expr-overview-pca-before-qc-reads, fig.cap = "PCA plot of the blischak data"}
scater::plotPCA(reads[endog_genes, ],
                ntop = 500,
                colour_by = "batch",
                size_by = "total_features",
                shape_by = "individual",
                exprs_values = "counts")
```

```{r expr-overview-pca-after-qc-reads, fig.cap = "PCA plot of the blischak data"}
scater::plotPCA(reads.qc[endog_genes, ],
                ntop = 500,
                colour_by = "batch",
                size_by = "total_features",
                shape_by = "individual",
                exprs_values = "counts")
```

```{r expr-overview-tsne-before-qc-reads, fig.cap = "tSNE map of the blischak data"}
scater::plotTSNE(reads[endog_genes, ],
                 ntop = 500,
                 perplexity = 130,
                 colour_by = "batch",
                 size_by = "total_features",
                 shape_by = "individual",
                 exprs_values = "counts",
                 rand_seed = 123456)
```

```{r expr-overview-tsne-after-qc-reads, fig.cap = "tSNE map of the blischak data"}
scater::plotTSNE(reads.qc[endog_genes, ],
                 ntop = 500,
                 perplexity = 130,
                 colour_by = "batch",
                 size_by = "total_features",
                 shape_by = "individual",
                 exprs_values = "counts",
                 rand_seed = 123456)
```

```{r expr-overview-tsne-after-qc-exercise2-1, fig.cap = "tSNE map of the blischak data (perplexity = 10)", echo=FALSE}
scater::plotTSNE(reads.qc[endog_genes, ],
                 ntop = 500,
                 perplexity = 10,
                 colour_by = "batch",
                 size_by = "total_features",
                 shape_by = "individual",
                 exprs_values = "counts",
                 rand_seed = 123456)
```

```{r expr-overview-tsne-after-qc-exercise2-2, fig.cap = "tSNE map of the blischak data (perplexity = 200)", echo=FALSE}
scater::plotTSNE(reads.qc[endog_genes, ],
                 ntop = 500,
                 perplexity = 200,
                 colour_by = "batch",
                 size_by = "total_features",
                 shape_by = "individual",
                 exprs_values = "counts",
                 rand_seed = 123456)
```
